-- Optional seed data pulled from scripts/03-seed-data.sql.
-- Run automatically when executing `supabase db reset`.

insert into organizations (name, description, primary_interest, contact_person, contact_email, location, type, is_approved) values
('Qendra për Ekonomi Qarkore', 'Organizatë që promovon ekonominë qarkore në Kosovë', 'Ekonomi qarkore', 'Arben Krasniqi', 'info@ceq.org', 'Prishtinë, Kosovë', 'OJQ', true),
('EcoTech Solutions', 'Kompani që ofron zgjidhje teknologjike për qëndrueshmëri', 'Teknologji e gjelbër', 'Blerta Hoxha', 'contact@ecotech.co', 'Prizren, Kosovë', 'Kompani', true),
('Green Future Kosovo', 'Ndërmarrje sociale për projekte të gjelbra', 'Energji e ripërtëritshme', 'Driton Berisha', 'hello@greenfuture.org', 'Pejë, Kosovë', 'Ndërmarrje Sociale', true),
('Reciklimi Plus', 'Kompani për riciklim dhe menaxhim mbetjesh', 'Riciklim', 'Fatmire Gashi', 'info@reciklimi.com', 'Gjilan, Kosovë', 'Kompani', true),
('Bujqësia e Qëndrueshme', 'OJQ për promovimin e bujqësisë organike', 'Bujqësi e qëndrueshme', 'Mentor Kelmendi', 'contact@bujqesia.org', 'Ferizaj, Kosovë', 'OJQ', true);

insert into artikuj (title, content, author_id, is_published, category, tags) values
('Hyrje në Ekonominë Qarkore', 'Ekonomia qarkore është një model ekonomik që synon eliminimin e mbetjeve dhe përdorimin e vazhdueshëm të burimeve. Ky artikull shpjegon parimet bazë të ekonomisë qarkore dhe përfitimet e saj për mjedisin dhe ekonominë.', (select id from users where role = 'Admin' limit 1), true, 'Ekonomi qarkore', array['ekonomi', 'qëndrueshmëri', 'mjedis']),
('Riciklimi në Kosovë: Sfidat dhe Mundësitë', 'Analiza e gjendjes aktuale të riciklimit në Kosovë, sfidat kryesore dhe mundësitë për përmirësim. Artikulli përfshin rekomandime për politikëbërësit dhe qytetarët.', (select id from users where role = 'Admin' limit 1), true, 'Riciklim', array['riciklim', 'Kosovë', 'politika']),
('Energjia e Ripërtëritshme: E Ardhmja e Kosovës', 'Potenciali i Kosovës për energji të ripërtëritshme, duke përfshirë energjinë diellore, erën dhe hidro. Diskutohen investimet e nevojshme dhe përfitimet ekonomike.', (select id from users where role = 'Admin' limit 1), true, 'Energji e ripërtëritshme', array['energji', 'diell', 'erë']),
('Biodiversiteti i Kosovës dhe Konservimi', 'Kosova është shtëpia e një biodiversiteti të pasur me mbi 1800 lloje bimësh dhe 300 lloje shtazësh. Ky artikull eksploron zonat e mbrojtura, sfidat e biodiversitetit dhe iniciativat për konservimin e natyrës.', (select id from users where role = 'Admin' limit 1), true, 'Biodiversitet', array['biodiversitet', 'konservim', 'natyrë']),
('Bujqësia e Qëndrueshme në Kosovë', 'Transformimi i bujqësisë kosovare drejt praktikave të qëndrueshme. Diskutohen teknikat organike, menaxhimi i ujit dhe përfitimet ekonomike për fermerët vendas.', (select id from users where role = 'Admin' limit 1), true, 'Bujqësi e qëndrueshme', array['bujqësi', 'organike', 'fermerë']),
('Ndikimi i Ndryshimeve Klimatike në Kosovë', 'Analiza e efekteve të ndryshimeve klimatike në territorin e Kosovës, duke përfshirë thatësirën, përmbytjet dhe ndryshimet në mot. Propozojmë strategji për përshtatje dhe mitigim.', (select id from users where role = 'Admin' limit 1), true, 'Ndryshimet klimatike', array['klima', 'përshtatje', 'mitigim']),
('Ndërmarrësi i Gjelbër: Oportunitetet në Kosovë', 'Udhëzues për fillimin e bizneseve të gjelbra në Kosovë. Përfshin ide biznesi, mbështetje financiare dhe tregjet për produktet e qëndrueshme.', (select id from users where role = 'Admin' limit 1), true, 'Ndërmarrësi i gjelbër', array['biznes', 'gjelbër', 'investime']),
('Menaxhimi i Burimeve të Ujit në Kosovë', 'Gjendja e burimeve ujore në Kosovë dhe sfidat e menaxhimit të tyre. Diskutohen strategjitë për ruajtjen e ujit dhe përdorimin efikas të tij.', (select id from users where role = 'Admin' limit 1), true, 'Menaxhimi i ujit', array['ujë', 'burime', 'ruajtje']),
('Qëndrueshmëria Urbane në Qytetet e Kosovës', 'Iniciativat për zhvillimin e qëndrueshëm urban në Prishtinë dhe qytetet e tjera. Përfshin transportin publik, ndërtimin e gjelbër dhe menaxhimin e mbetjeve urbane.', (select id from users where role = 'Admin' limit 1), true, 'Qëndrueshmëria urbane', array['qytet', 'transport', 'ndërtim']),
('Edukim Ambiental për të Ardhmen e Kosovës', 'Rëndësia e edukimit ambiental në shkollat kosovare. Programe, aktivitete dhe materiale për rritjen e ndërgjegjësimit për mjedisin tek të rinjtë.', (select id from users where role = 'Admin' limit 1), true, 'Edukim ambiental', array['edukim', 'rinia', 'ndërgjegjësim']),
('Energjia Diellore: Potenciali i Madh i Kosovës', 'Kosova ka një nga potencialet më të mëdha për energjinë diellore në rajon. Ky artikull analizon kushtet gjeografike dhe ekonomike për zhvillimin e këtij sektori.', (select id from users where role = 'Admin' limit 1), true, 'Energji diellore', array['diell', 'potencial', 'investime']),
('Riciklimi i Plastikës: Një sfidë për Kosovën', 'Problemi i mbetjeve plastike në Kosovë dhe zgjidhjet për riciklimin e tyre. Përfshin teknologjitë moderne dhe praktikat më të mira ndërkombëtare.', (select id from users where role = 'Admin' limit 1), true, 'Riciklim plastike', array['plastikë', 'mbetje', 'teknologji']),
('Pyjet e Kosovës dhe Rëndësia e tyre për Klimën', 'Pyjet kosovare si sink i karbonit dhe roli i tyre në luftën kundër ndryshimeve klimatike. Strategjitë për mbrojtjen dhe rigjallërimin e pyjeve.', (select id from users where role = 'Admin' limit 1), true, 'Pyjet dhe klima', array['pyje', 'karbon', 'rigjallërim']);

insert into tregu_listime (created_by_user_id, title, description, category, price, unit, location, quantity, listing_type, is_approved) values
((select id from users where role = 'Admin' limit 1), 'Materiale plastike të riciklueshme', 'Plastikë e pastër PET dhe HDPE, e përshtatshme për riciklim. Materiali është i sortuar dhe i pastruar.', 'Materiale të riciklueshme', 0.50, 'kg', 'Prishtinë, Kosovë', '500-1000 kg', 'shes', true),
((select id from users where role = 'Admin' limit 1), 'Panele diellore të përdorura', 'Panele diellore në gjendje të mirë, të përshtatshme për projekte të vogla. Efikasiteti 80% i kapacitetit origjinal.', 'Energji e ripërtëritshme', 150.00, 'copë', 'Prizren, Kosovë', '10-20 copë', 'shes', true),
((select id from users where role = 'Admin' limit 1), 'Kërkoj materiale ndërtimi të ricikluara', 'Jam në kërkim të materialeve të ricikluara për ndërtim, siç janë tulla, beton i thyer, dhe materiale të tjera.', 'Materiale të riciklueshme', 20.00, 'ton', 'Mitrovicë, Kosovë', '5-10 ton', 'blej', true),

-- 10 listings for selling (shes)
((select id from users where role = 'Admin' limit 1), 'Perime Organike nga Fshati', 'Domate, patate dhe speca të kultivuara pa pesticide. Të korrura të freskëta dhe të paketuar me kujdes.', 'Ushqim dhe bujqësi', 2.50, 'kg', 'Gjilan, Kosovë', '200-500 kg', 'shes', true),
((select id from users where role = 'Admin' limit 1), 'Tekstile të Ricikluara për Rrobaqepësi', 'Pëlhurë dhe inde të ricikluara cilësore, perfekte për prodhimin e rrobave të qëndrueshme dhe aksesorëve.', 'Tekstile', 5.00, 'metër', 'Ferizaj, Kosovë', '100-300 metra', 'shes', true),
((select id from users where role = 'Admin' limit 1), 'Batteri për Bicikleta Elektrike', 'Batteri litium-ion të ricikluara dhe rinovuar, ideale për projekte të transportit të gjelbër.', 'Elektronikë', 120.00, 'copë', 'Prishtinë, Kosovë', '15-25 copë', 'shes', true),
((select id from users where role = 'Admin' limit 1), 'Mjaltë Organik nga Bjeshkët e Sharrit', 'Mjaltë i pastër akacie dhe gështenjë, prodhuar nga bletët në zonat e mbrojtura malore.', 'Ushqim dhe bujqësi', 8.00, 'kavanoz', 'Prizren, Kosovë', '50-100 kavanoz', 'shes', true),
((select id from users where role = 'Admin' limit 1), 'Sisteme për Mbledhjen e Ujit të Shiut', 'Sisteme komplekse për mbledhjen dhe filtrimin e ujit të shiut, perfekte për shtëpi dhe ferma.', 'Produkte të qëndrueshme', 250.00, 'sistem', 'Pejë, Kosovë', '5-15 sisteme', 'shes', true),
((select id from users where role = 'Admin' limit 1), 'Farëra Organike për Bujqësi', 'Përzgjedhje e farërave organike lokale: grurë, misër dhe perime sezonale.', 'Ushqim dhe bujqësi', 15.00, 'kg', 'Mitrovicë, Kosovë', '25-50 kg', 'shes', true),
((select id from users where role = 'Admin' limit 1), 'Kompjuterë të Riciklurar për Shkolla', 'Laptop dhe desktop të rinovuar, perfekt për programe edukative dhe trajnime digjitale.', 'Elektronikë', 200.00, 'copë', 'Prishtinë, Kosovë', '20-40 copë', 'shes', true),
((select id from users where role = 'Admin' limit 1), 'Produkte Kosmetike Natyrale', 'Kremra dhe shpëlarës të prodhuar nga përbërës natyrorë vendas, pa kimikate sintetike.', 'Produkte të qëndrueshme', 12.00, 'flakon', 'Gjilan, Kosovë', '100-200 flakon', 'shes', true),
((select id from users where role = 'Admin' limit 1), 'Pellumba për Energji Diellore', 'Pellumba diellore efikase për ngrohje të ujit, ideale për shtëpi dhe biznese të vogla.', 'Energji e ripërtëritshme', 180.00, 'sistem', 'Ferizaj, Kosovë', '8-15 sisteme', 'shes', true),
((select id from users where role = 'Admin' limit 1), 'Shërbime Konsultimi për Ekonomi Qarkore', 'Konsultime ekspertësh për implementimin e praktikave të ekonomisë qarkore në biznese.', 'Shërbime', 100.00, 'orë', 'Prishtinë, Kosovë', '20-50 orë', 'shes', true),

-- 10 listings for buying (blej)
((select id from users where role = 'Admin' limit 1), 'Kërkoj Metale të Ricikluara', 'Nevojë për metale të ricikluara: bakër, aluminiun dhe çelik për projekte industriale.', 'Materiale të riciklueshme', 3.00, 'kg', 'Prishtinë, Kosovë', '1000-2000 kg', 'blej', true),
((select id from users where role = 'Admin' limit 1), 'Blej Komponente për Panele Diellore', 'Kërkoj inverterë dhe kontrollues për sisteme diellore, të rinj ose të rinovuar.', 'Energji e ripërtëritshme', 80.00, 'copë', 'Prizren, Kosovë', '30-50 copë', 'blej', true),
((select id from users where role = 'Admin' limit 1), 'Farëra Organike për Fermë', 'Nevojë për farëra organike të perimeve dhe drithërave për zgjerimin e fermës sonë.', 'Ushqim dhe bujqësi', 10.00, 'kg', 'Pejë, Kosovë', '50-100 kg', 'blej', true),
((select id from users where role = 'Admin' limit 1), 'Kërkoj Tekstile të Ricikluara', 'Blej pëlhurë dhe inde të ricikluara për prodhimin e rrobave dhe aksesorëve të qëndrueshëm.', 'Tekstile', 4.00, 'metër', 'Gjilan, Kosovë', '200-400 metra', 'blej', true),
((select id from users where role = 'Admin' limit 1), 'Batteri për Automjete Elektrike', 'Nevojë për bateri litium-ion të ricikluara për riparimin e automjeteve elektrike.', 'Elektronikë', 150.00, 'copë', 'Ferizaj, Kosovë', '10-20 copë', 'blej', true),
((select id from users where role = 'Admin' limit 1), 'Materiale Ndërtimi të Qëndrueshëm', 'Kërkoj materiale ndërtimi ekologjike: dru i certifikuar, izolime natyrale dhe çimento të gjelbër.', 'Materiale të riciklueshme', 25.00, 'm³', 'Mitrovicë, Kosovë', '20-50 m³', 'blej', true),
((select id from users where role = 'Admin' limit 1), 'Kërkoj Furnizues për Biokarburant', 'Nevojë për prodhues të biokarburantit për projektin tonë të transportit të gjelbër.', 'Energji e ripërtëritshme', 1.20, 'litër', 'Prishtinë, Kosovë', '5000-10000 litra', 'blej', true),
((select id from users where role = 'Admin' limit 1), 'Komponente Elektronike të Ricikluara', 'Blej çipa dhe komponente elektronike të ricikluara për riparimin dhe ripërdorimin.', 'Elektronikë', 2.00, 'copë', 'Prizren, Kosovë', '500-1000 copë', 'blej', true),
((select id from users where role = 'Admin' limit 1), 'Përbërës Natyrorë për Kosmetikë', 'Nevojë për vajra esenciale dhe ekstrakte bimore për prodhimin e produkteve kozmetike natyrale.', 'Produkte të qëndrueshme', 15.00, 'kg', 'Gjilan, Kosovë', '30-60 kg', 'blej', true),
((select id from users where role = 'Admin' limit 1), 'Ekipamente për Energji të Erës', 'Kërkoj gjeneratorë dhe propeller për sisteme të vogla të energjisë së erës.', 'Energji e ripërtëritshme', 300.00, 'sistem', 'Ferizaj, Kosovë', '3-8 sisteme', 'blej', true);
